project:
  type: website
  output-dir: docs

website:
  title: "Induction Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: R.qmd
        text: R
      - href: Python.qmd
        text: Python
      - href: data_ethics.qmd
        text: Data Ethics Case Studies
      - href: files.qmd
        text: Files
      - href: other_slides.qmd
        text: Other

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



