project:
  type: website
  output-dir: docs

website:
  title: "Induction Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: R.qmd
      - href: Python.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



